### ISSUE TITLE
 [Error transcribing chunk 0]

### ISSUE THREAD

**Issue by 0xSeanG** [chhoumann/PodNotes#102]
Transcription is failing - {{transcript}} is being replaced by [Error transcribing chunk 0] in the target note.

Project API Key has full permissions:
![image](https://github.com/user-attachments/assets/48aff8db-2baa-4445-b5cd-f8fe5c9d6940)

**Comment by chhoumann** [comment]
Hey @0xSeanG, can you provide me with the episode that's failing? I'll take a look!

**Comment by 0xSeanG** [comment]
@chhoumann  
![image](https://github.com/user-attachments/assets/b07aa62e-eb0a-4e31-98ca-1163ec7830f3)

**Comment by chhoumann** [comment]
It seems to work for me on those episodes. Are you getting any errors in the developer console? You can access it with `CTRL + Shift + i`, or CMD instead of CTRL if you're on Mac.

**Comment by 0xSeanG** [comment]
May be PEBCAK but I am not seeing the connection:

![image](https://github.com/user-attachments/assets/5b8fdc2a-c70e-4c4c-aa45-efdf0afbb42b)


![image](https://github.com/user-attachments/assets/13553730-2193-4ac7-a6ef-70c6f327ccc0)

**Comment by chhoumann** [comment]
After OpenAI introduced the new Project-based management of Osage and API keys, I had an issue where not all projects used my billing information. One was in my personal "default" project and another in my business' projects - and the billing isn't shared between them, of course. 

So can you check that you've set up billing for the project & organization your API key is associated with? Because it seems like there may not be credits available.

**Comment by 0xSeanG** [comment]
Yes - billing issue in the project - thank you!

**Comment by chhoumann** [comment]
Happy to help. Hope you find the new feature useful!
