### ISSUE TITLE
[Feature request] Add a link to unversal podcast (pod.link)

### ISSUE THREAD

**Issue by danieltomasz** [chhoumann/PodNotes#36]
Would be great to have the link to the episode resolved on pod.link if the podcast is present there
 https://pod.link/
(universal link to different streaming services), I have a shortcut that is doing this for link from my podcast app
I might elaborate more and provide more details and examples if this might be useful idea

(Motivation: often  I want to share a link to a podcast  episode to my friends without googling)

**Comment by chhoumann** [comment]
Hey @danieltomasz,

Thanks for the suggestion!
I'd be able to do this for the podcast itself, but don't think I can for episodes.
It looks like pod.link uses iTunes IDs to link to podcasts, but I have no idea what they use to search for episodes.

So e.g. linking like this https://pod.link/1430315931 would be feasible, but not to any episode directly.
I can imagine, since they are part of a larger podcast insights company, that they have some internal APIs / can bear the cost of external ones. Not sure though.

Some analysis from me:
Here's the pod.link URL for The Daily Stoic's episode, `What Will This Cause? | Ask Daily Stoic`: `https://pod.link/1430315931/episode/f2e120acf5c598551bfc1228a84ef44f`

Now, `1430315931` is the iTunes collection ID for The Daily Stoic podcast.
`f2e120acf5c598551bfc1228a84ef44f` seems to be some kind of episode ID.

The plugin already searches for podcasts, so getting their IDs is trivial.
iTunes also allows searching for episodes. Here's the link for searching for the aforementioned episode: `https://itunes.apple.com/lookup?id=1430315931&media=podcast&entity=podcastEpisode&term=What Will This Cause? | Ask Daily Stoic`.

`id` is the collection ID for The Daily Stoic again. We're searching for media = `podcast` and entities of type `podcastEpisode` (undocumented in iTunes API), and for the term. This, at the time of writing, returns 51 results. Selecting the proper episode from those gives us this result:
```json
{
      "artworkUrl60": "https://is2-ssl.mzstatic.com/image/thumb/Podcasts126/v4/b5/cb/58/b5cb5840-8ae3-17bc-f842-82caabdd71a0/mza_18392220335995768370.jpeg/60x60bb.jpg",
      "contentAdvisoryRating": "Clean",
      "trackViewUrl": "https://podcasts.apple.com/us/podcast/what-will-this-cause-ask-daily-stoic/id1430315931?i=1000598781354&uo=4",
      "collectionViewUrl": "https://itunes.apple.com/us/podcast/the-daily-stoic/id1430315931?mt=2&uo=4",
      "genres": [
        {
          "name": "Education",
          "id": "1304"
        }
      ],
      "episodeGuid": "gid://art19-episode-locator/V0/MF6ciLgUiO2jyrjxa76aXnOI4ey_d81a7YINg7tQnJQ",
      "description": "When horrible things happen to us, our instinct is always to ask why me? Why this? Why now? It’s understandable, but it’s also irrelevant and unhelpful, because those questions have no answer. At least no answer that you can do anything about or take any comfort from. Besides, life has a better question. One it is constantly asking us, one that Michael Lewis to his credit has fully embraced: what will this cause? Will it put us out of commission or give us a new mission? Will it cause good things or bad things?\n\nAnd in today's Ask Daily Stoic, Ryan answers questions as part of a Stoicism virtual discussion. Topics include the best ways to teach Stoic wisdom to kids and why a formal education doesn't necessarily equate to practical intelligence. \n\n✉️  Sign up for the Daily Stoic email: https://dailystoic.com/dailyemail\n\n🏛 Check out the Daily Stoic Store for Stoic inspired products, signed books, and more.\n\n📱 Follow us: Instagram, Twitter, YouTube, TikTok, Facebook\n\nSee Privacy Policy at https://art19.com/privacy and California Privacy Notice at https://art19.com/privacy#do-not-sell-my-info.",
      "releaseDate": "2023-02-09T06:00:00Z",
      "trackTimeMillis": 528000,
      "artistIds": [],
      "shortDescription": "",
      "trackId": 1000598781354,
      "trackName": "What Will This Cause? | Ask Daily Stoic",
      "feedUrl": "https://rss.art19.com/the-daily-stoic",
      "previewUrl": "https://dts.podtrac.com/redirect.mp3/chtbl.com/track/9EE2G/pdst.fm/e/rss.art19.com/episodes/f5f81af4-7d86-43f1-b6ef-ec4b342a00b7.mp3?rss_browser=BAhJIglpVE1TBjoGRVQ%3D--4577cbcc3cc5282be318e551563630a2c5c2f06f",
      "closedCaptioning": "none",
      "collectionId": 1430315931,
      "collectionName": "The Daily Stoic",
      "country": "USA",
      "episodeUrl": "https://dts.podtrac.com/redirect.mp3/chtbl.com/track/9EE2G/pdst.fm/e/rss.art19.com/episodes/f5f81af4-7d86-43f1-b6ef-ec4b342a00b7.mp3?rss_browser=BAhJIglpVE1TBjoGRVQ%3D--4577cbcc3cc5282be318e551563630a2c5c2f06f",
      "artworkUrl600": "https://is2-ssl.mzstatic.com/image/thumb/Podcasts126/v4/b5/cb/58/b5cb5840-8ae3-17bc-f842-82caabdd71a0/mza_18392220335995768370.jpeg/600x600bb.jpg",
      "artworkUrl160": "https://is2-ssl.mzstatic.com/image/thumb/Podcasts126/v4/b5/cb/58/b5cb5840-8ae3-17bc-f842-82caabdd71a0/mza_18392220335995768370.jpeg/160x160bb.jpg",
      "episodeFileExtension": "mp3",
      "episodeContentType": "audio",
      "kind": "podcast-episode",
      "wrapperType": "podcastEpisode"
    },
```

Now, unfortunately, the pod.link episode ID does not seem to appear anywhere here. That doesn't seem to correspond with the `trackId` either, which one would have expected.
It doesn't appear in the RSS feed either.

Further analysis of the pod.link site leads me to believe it is server-side-rendered with caching, as it already has all the data it needs. Shown in `<script>` where it loads it into `window.__STATE__` as an object. And that's only the most recent episodes.

UPDATE: figured it out. `https://pod.link/1430315931.json` returns the items we need.
Coming in latest release :)

**Comment by chhoumann** [comment]
The solution is kinda hacky, though. So it may break. But for now, we can enjoy it!
